<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{

	public function loadUserByUsername($email){
        return $this->createQueryBuilder('u')
            ->where('u.email = :email')
            ->setParameter('email', $email)
            ->getQuery()
            ->getOneOrNullResult();
	}

    /**
     * @return Query Returns an array of Query objects
     *
     */
	public function getQueryUsers()
    {
        return $this->createQueryBuilder('user')
            ->innerJoin('user.country', 'country')
            ->addSelect('country')
            ->orderBy('user.id', 'DESC')
            ->getQuery()
        ;
    }
}
